title: Just Just
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gilntk.github.io/uvkqsg

aux_links:
  Template Repository: https://github.com/gilntk/uvkqsg

nav_enabled: true


plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap
