title: UV-K5 Quick Start Guide
description: Your quick reference guide to the Quansheng UV-K5 Handheld Transmitter
theme: just-the-docs

url: https://gilntk.github.io/uvkqsg

aux_links:
  Template Repository: https://github.com/gilntk/uvkqsg

# nav_enabled: true


# plugins:
#  - jekyll-sitemap
